### ISSUE TITLE
Adding video tutorial

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/oscar-cli#14]
Hi!

Have you uploaded the video tutorial shown in https://www.egi.eu/event/egi2022/ somewhere?

It would be nice to have it linked in https://github.com/grycap/oscar-cli/blob/main/README.md

Thanks!

**Comment by gmolto** [comment]
Hi Sebastián,

Sure thing. The video is now available in: https://youtu.be/itaKJyd9QX4

We will include it in the documentation of OSCAR, probably in https://docs.oscar.grycap.net

Cheers.

**Comment by sebastian-luna-valero** [comment]
Thanks!

Could you also link https://docs.oscar.grycap.net/ from https://github.com/grycap/oscar-cli/blob/main/README.md?

Best regards,
Sebastian
